// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdvH_ucS_rlFZ4E6pirMg4e8Wu-_p_QY',
    appId: '1:371275512225:web:8dbefc35474fc32634f3e0',
    messagingSenderId: '371275512225',
    projectId: 'graduation-app-3dc18',
    authDomain: 'graduation-app-3dc18.firebaseapp.com',
    storageBucket: 'graduation-app-3dc18.firebasestorage.app',
    measurementId: 'G-T9PXR3JV5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5U-LSxLIOp9FuxWtVjvYVWmBr7U_MZ10',
    appId: '1:371275512225:android:e02b60328fb5a21134f3e0',
    messagingSenderId: '371275512225',
    projectId: 'graduation-app-3dc18',
    storageBucket: 'graduation-app-3dc18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCynVTT02ZHYBz6XbyAJuQ9UQtaFIFKHpk',
    appId: '1:371275512225:ios:59151623d4635f7634f3e0',
    messagingSenderId: '371275512225',
    projectId: 'graduation-app-3dc18',
    storageBucket: 'graduation-app-3dc18.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCynVTT02ZHYBz6XbyAJuQ9UQtaFIFKHpk',
    appId: '1:371275512225:ios:59151623d4635f7634f3e0',
    messagingSenderId: '371275512225',
    projectId: 'graduation-app-3dc18',
    storageBucket: 'graduation-app-3dc18.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbdvH_ucS_rlFZ4E6pirMg4e8Wu-_p_QY',
    appId: '1:371275512225:web:e192666917c965b634f3e0',
    messagingSenderId: '371275512225',
    projectId: 'graduation-app-3dc18',
    authDomain: 'graduation-app-3dc18.firebaseapp.com',
    storageBucket: 'graduation-app-3dc18.firebasestorage.app',
    measurementId: 'G-V1KNXHS03R',
  );
}
